### ISSUE TITLE
npm install fails on linux mint

### ISSUE THREAD

**Issue by bicubic** [node-webrtc/node-webrtc#114]
```
me@mintvm ~/node $ uname -rvm && node -v && npm -v
3.8.0-19-generic #30-Ubuntu SMP Wed May 1 16:36:13 UTC 2013 i686
v0.10.22
1.3.14
me@mintvm ~/node $ npm install wrtc
npm http GET https://registry.npmjs.org/wrtc
npm http 304 https://registry.npmjs.org/wrtc
npm http GET https://registry.npmjs.org/rsvp
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/node-gyp
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/node-gyp
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/rsvp
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/osenv
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/ansi
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5

> wrtc@0.0.19 install /home/me/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-ia32.tar.gz
node-pre-gyp http 404 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-ia32.tar.gz
node-pre-gyp ERR! Source compile required: 404 status code downloading tarball 
make: Entering directory `/home/me/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=ia32 r5982 Release
Preparing directories ... done
Cloning depot tools ... error (see build.log for details): make: *** [/dev/null] Error 255
make: Leaving directory `/home/me/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/me/node_modules/wrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.0-19-generic
gyp ERR! command "/usr/local/bin/node" "/home/me/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.19" "--patch=19" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/home/me/node_modules/wrtc/lib/binding" "--remote_path=./wrtc/v0.0.19/Release/" "--package_name=wrtc-v0.0.19-node-v11-linux-ia32.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-ia32.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-ia32.tar.gz"
gyp ERR! cwd /home/me/node_modules/wrtc
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.19 --patch=19 --runtime=node --node_abi=node-v11 --platform=linux --arch=ia32 --target_arch=ia32 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/home/me/node_modules/wrtc/lib/binding --remote_path=./wrtc/v0.0.19/Release/ --package_name=wrtc-v0.0.19-node-v11-linux-ia32.tar.gz --staged_tarball=build/stage/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-ia32.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/me/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.8.0-19-generic
node-pre-gyp ERR! command "node" "/home/me/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/me/node_modules/wrtc
node-pre-gyp ERR! node -v v0.10.22
node-pre-gyp ERR! node-pre-gyp -v v0.5.9
node-pre-gyp ERR! not ok 
npm ERR! wrtc@0.0.19 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.19 install script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wrtc"
npm ERR! cwd /home/me/node
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/me/node/npm-debug.log 
```

**Comment by chris--** [comment]
I think this is the same as #112

**Comment by bicubic** [comment]
Hm, I get the same error  after git clone and npm install: Cloning depot tools ... error (see build.log for details): make: **\* [/dev/null] Error 255, nothing about third_party
build.log is empty by the way

**Comment by chris--** [comment]
I hit the same problem. For me, manually creating the `third_party`directory up front helped.

**Comment by bicubic** [comment]
Ok so I had a slightly worse case. Creating `third_party` still caused the same error. Creating `third_party/depot_tools` allowed the compilation to proceed, but then the build process skipped cloning it. I manually cloned depot tools and now install still fails:

```
make: Entering directory `/home/me/node/wrtc/node-webrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 r5982 Release
Preparing directories ... done
Cloning depot tools ... skip
Configuring gclient ... done
Syncing upstream libjingle ... done
Executing runhooks ... ermake: *** [/dev/null] Error 255
make: Leaving directory `/home/me/node/wrtc/node-webrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/me/node/wrtc/node-webrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.7-x86_64-linode38
gyp ERR! command "/usr/bin/nodejs" "/home/me/node/wrtc/node-webrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.19" "--patch=19" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/home/me/node/wrtc/node-webrtc/lib/binding" "--remote_path=./wrtc/v0.0.19/Release/" "--package_name=wrtc-v0.0.19-node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-x64.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-x64.tar.gz"
gyp ERR! cwd /home/me/node/wrtc/node-webrtc
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.19 --patch=19 --runtime=node --node_abi=node-v11 --platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/home/me/node/wrtc/node-webrtc/lib/binding --remote_path=./wrtc/v0.0.19/Release/ --package_name=wrtc-v0.0.19-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.19/Release/wrtc-v0.0.19-node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/me/node/wrtc/node-webrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:743:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
node-pre-gyp ERR! System Linux 3.13.7-x86_64-linode38
node-pre-gyp ERR! command "node" "/home/me/node/wrtc/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/me/node/wrtc/node-webrtc
node-pre-gyp ERR! node -v v0.10.26
node-pre-gyp ERR! node-pre-gyp -v v0.5.10
node-pre-gyp ERR! not ok 

npm ERR! wrtc@0.0.19 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.19 install script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.7-x86_64-linode38
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/me/node/wrtc/node-webrtc
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/me/node/wrtc/node-webrtc/npm-debug.log
npm ERR! not ok code 0
```

**Comment by modeswitch** [comment]
Can you paste the contents of `build.log`? It'll be in `node_modules/wrtc`.

**Comment by bicubic** [comment]
`build.log` was empty. I ended up updating libc to 2.17 at which point the prebuilt binary passed tests and install succeeded, so I won't be able to help with this issue any more. Perhaps my last build error was due to old version libc? If so, an error message to that effect would be helpful to future users.

**Comment by modeswitch** [comment]
In that case, I'm aware of the issue. I need to make the binary modules on an older machine so that it's compatible with more libc versions. That will happen in an upcoming release.
