### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by bukzor** [node-webrtc/node-webrtc#131]
First of all, thank you very much for this work. It works really well when I get it to build.
This issue is previously reported but closed, so I'm filing a fresh issue.

I find the build system very hard to debug though. The first order of business would be to enable the build failure to show me the actual failure message from make/gcc. Secondarily the fact that build.log is always blank makes it hard to know what went wrong.

```
$ npm install

> wrtc@0.0.22 install /nail/home/buck/trees/theirs/node-webrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz
[wrtc] Command failed:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:901:3

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile
make: Entering directory `/nail/home/buck/trees/theirs/node-webrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 r5982 Release
Preparing directories ... done
Cloning depot tools ... error (see build.log for details): make: *** [/dev/null] Error 255
make: Leaving directory `/nail/home/buck/trees/theirs/node-webrtc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nail/home/buck/trees/theirs/node-webrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.0-35-generic
gyp ERR! command "/usr/bin/nodejs" "/nail/home/buck/trees/theirs/node-webrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.22" "--patch=22" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/nail/home/buck/trees/theirs/node-webrtc/lib/binding" "--remote_path=./wrtc/v0.0.22/Release/" "--package_name=wrtc-v0.0.22-node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz"
gyp ERR! cwd /nail/home/buck/trees/theirs/node-webrtc
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.22 --patch=22 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/nail/home/buck/trees/theirs/node-webrtc/lib/binding --remote_path=./wrtc/v0.0.22/Release/ --package_name=wrtc-v0.0.22-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/nail/home/buck/trees/theirs/node-webrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.8.0-35-generic
node-pre-gyp ERR! command "node" "/nail/home/buck/trees/theirs/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /nail/home/buck/trees/theirs/node-webrtc
node-pre-gyp ERR! node -v v0.10.17
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.22 --patch=22 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/nail/home/buck/trees/theirs/node-webrtc/lib/binding --remote_path=./wrtc/v0.0.22/Release/ --package_name=wrtc-v0.0.22-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz' (1)
npm ERR! weird error 1
npm ERR! not ok code 0

$ cat build.log
(no output)

$ ls -l third_party/
total 4
drwxr-xr-x 2 buck users 4096 2014-07-25 12:02 libwebrtc
```

Creating third_party/depot_tools/ gets me a bit farther, but not by much:

```
$ npm install

> wrtc@0.0.22 install /nail/home/buck/trees/theirs/node-webrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz
[wrtc] Command failed:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:901:3

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile
make: Entering directory `/nail/home/buck/trees/theirs/node-webrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 r5982 Release
Preparing directories ... done
Cloning depot tools ... skip
Configuring gclient ...
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
make: *** [/dev/null] Error 8
make: Leaving directory `/nail/home/buck/trees/theirs/node-webrtc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nail/home/buck/trees/theirs/node-webrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.0-35-generic
gyp ERR! command "/usr/bin/nodejs" "/nail/home/buck/trees/theirs/node-webrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.22" "--patch=22" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/nail/home/buck/trees/theirs/node-webrtc/lib/binding" "--remote_path=./wrtc/v0.0.22/Release/" "--package_name=wrtc-v0.0.22-node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz"
gyp ERR! cwd /nail/home/buck/trees/theirs/node-webrtc
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.22 --patch=22 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/nail/home/buck/trees/theirs/node-webrtc/lib/binding --remote_path=./wrtc/v0.0.22/Release/ --package_name=wrtc-v0.0.22-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/nail/home/buck/trees/theirs/node-webrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.8.0-35-generic
node-pre-gyp ERR! command "node" "/nail/home/buck/trees/theirs/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /nail/home/buck/trees/theirs/node-webrtc
node-pre-gyp ERR! node -v v0.10.17
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.22 --patch=22 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/nail/home/buck/trees/theirs/node-webrtc/lib/binding --remote_path=./wrtc/v0.0.22/Release/ --package_name=wrtc-v0.0.22-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.22/Release/wrtc-v0.0.22-node-v11-linux-x64.tar.gz' (1)
npm ERR! weird error 1
npm ERR! not ok code 0

$ cat build.log
(no output)
```

**Comment by bukzor** [comment]
To finally track down the error, I had to pass `{ 'stdio': [0, 1, 2] }` as the second option to the spawn of git.

I was rewarded with this message:

```
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]
```

`-C` seems to be an option present in git 2.0 but not 1.9.
http://man7.org/linux/man-pages/man1/git.1.html

To emulate -C in older gits, can pass a cwd option to spawn.
I'll produce a pull-request shortly.

**Comment by bukzor** [comment]
#132

**Comment by modeswitch** [comment]
Awesome, thanks! I'll check out your patch this week. What distro/version are you running, btw?

**Comment by bukzor** [comment]
I'm using osx homebrew, but I installed git several weeks ago before the 2.0 release.

**Comment by modeswitch** [comment]
Latest version should build without issues, and requires fewer deps on linux. I'm still stripping out unneeded deps on osx.
