### ISSUE TITLE
Missing dependency on fresh install?

### ISSUE THREAD

**Issue by kevzettler** [node-webrtc/node-webrtc#148]
I'm seeing this after a fresh install not sure where this is coming from

``` shell
 root@24f76e9614b5:/var/node-webrtc {develop} ]$ node examples/bridge.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/var/node-webrtc/lib/binding/wrtc.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/node-webrtc/lib/peerconnection.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by kevzettler** [comment]
Also seeing it from `npm test`

``` shell
 npm test

> wrtc@0.0.29 test /var/node-webrtc
> node test/all.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/var/node-webrtc/lib/binding/wrtc.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/node-webrtc/lib/peerconnection.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! Test failed.  See above for more details.
```

**Comment by modeswitch** [comment]
It may mean the module failed to build. Which platform are you on?

**Comment by kevzettler** [comment]
@modeswitch 

``` shell
[ root@24f76e9614b5:/var/node-webrtc {develop} ]$ uname -a
Linux 24f76e9614b5 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kevzettler** [comment]
The only thing suspicious i'm seeing on install is:

``` shell
[ root@24f76e9614b5:/var/node-webrtc {develop} ]$ npm install
-
> ws@0.4.32 install /var/node-webrtc/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/node-webrtc/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/node-webrtc/node_modules/ws/build'
npm WARN cannot run in wd wrtc@0.0.29 node-pre-gyp install --fallback-to-build (wd=/var/node-webrtc)
node-static-alias@0.1.2 node_modules/node-static-alias
```

**Comment by modeswitch** [comment]
What's in build.log?

**Comment by kevzettler** [comment]
``` shell
Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --bucket chromium-webrtc-resources trunk/resources' took 1658.88 secs

________ running '/usr/bin/python trunk/build/gyp_chromium --depth=trunk trunk/all.gyp -Dextra_gyp_flag=0' in '/var/node-webrtc/third_party/libwebrtc'
Error: Command /usr/bin/python trunk/build/gyp_chromium --depth=trunk trunk/all.gyp -Dextra_gyp_flag=0 returned non-zero exit status 1 in /var/node-webrtc/third_party/libwebrtc
Generating gyp files from GN...
Updating projects from gyp files...
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --cflags gnome-keyring-1' returned exit status 1
```

**Comment by kevzettler** [comment]
I did't see there was a Dockerfile. Used that works great!

**Comment by modeswitch** [comment]
Great. I'm in the process of ripping libjingle apart so that this module is easier to build.
