### ISSUE TITLE
Does this still require depot_tools?

### ISSUE THREAD

**Issue by kevzettler** [node-webrtc/node-webrtc#149]
The link in the readme seems to have changed:

http://www.webrtc.org/reference/getting-started/prerequisite-sw

The readme also states that I should just be able to npm install once i've installed the various apt-get packages. Does it still depend on the depot_tools?

**Comment by modeswitch** [comment]
The install script should fetch depot_tools for you.

**Comment by modeswitch** [comment]
It looks like the build process for webrtc has changed. I'm investigating now.

**Comment by kevzettler** [comment]
see if this helps:

``` shell
[ root@d0639c47a856:/var/lol ]$ uname -a; npm -v; node -v
Linux d0639c47a856 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
2.1.14
v0.10.34
```

``` shell
[ root@d0639c47a856:/var/lol ]$ npm install wrtc

> wrtc@0.0.29 install /var/lol/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory `/var/lol/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 r5982 Release
Preparing directories ... done
Cloning depot tools ...  done
Configuring gclient ...  done
Syncing upstream libjingle ... emake: *** [/dev/null] Error 255
make: Leaving directory `/var/lol/node_modules/wrtc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/lol/node_modules/wrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/usr/local/bin/node" "/var/lol/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.29" "--patch=29" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/var/lol/node_modules/wrtc/lib/binding" "--module=/var/lol/node_modules/wrtc/lib/binding/wrtc.node" "--remote_path=./wrtc/v0.0.29/Release/" "--package_name=wrtc-v0.0.29-node-v11-linux-x64.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.29/Release/wrtc-v0.0.29-node-v11-linux-x64.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.29/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.29/Release/wrtc-v0.0.29-node-v11-linux-x64.tar.gz"
gyp ERR! cwd /var/lol/node_modules/wrtc
gyp ERR! node -v v0.10.34
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.29 --patch=29 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/var/lol/node_modules/wrtc/lib/binding --module=/var/lol/node_modules/wrtc/lib/binding/wrtc.node --remote_path=./wrtc/v0.0.29/Release/ --package_name=wrtc-v0.0.29-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.29/Release/wrtc-v0.0.29-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.29/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.29/Release/wrtc-v0.0.29-node-v11-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/lol/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.2.0-23-generic
node-pre-gyp ERR! command "node" "/var/lol/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/lol/node_modules/wrtc
node-pre-gyp ERR! node -v v0.10.34
node-pre-gyp ERR! node-pre-gyp -v v0.5.23
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.29 --patch=29 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/var/lol/node_modules/wrtc/lib/binding --module=/var/lol/node_modules/wrtc/lib/binding/wrtc.node --remote_path=./wrtc/v0.0.29/Release/ --package_name=wrtc-v0.0.29-node-v11-linux-x64.tar.gz --staged_tarball=build/stage/wrtc/v0.0.29/Release/wrtc-v0.0.29-node-v11-linux-x64.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.29/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.29/Release/wrtc-v0.0.29-node-v11-linux-x64.tar.gz' (1)
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "wrtc"
npm ERR! node v0.10.34
npm ERR! npm  v2.1.14
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.29 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.0.29 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lol/npm-debug.log
```
