### ISSUE TITLE
Can't install on Ubuntu 14.10

### ISSUE THREAD

**Issue by xenyou** [node-webrtc/node-webrtc#167]
I got this error.

```
$ npm install wrtc
\
> wrtc@0.0.49 install /home/xenyou/hoge/node_modules/wrtc
> node-gyp rebuild

make: Entering directory '/home/xenyou/hoge/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=linux CONFIGURATION=Release PYTHON=python
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (189 bytes)
POST git-upload-pack (198 bytes)
remote: Sending approximately 14.66 MiB ...
remote: Counting objects: 849, done
remote: Finding sources: 100% (849/849)
remote: Total 849 (delta 110), reused 470 (delta 110)
Receiving objects: 100% (849/849), 2.76 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (110/110), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (205 bytes)
POST git-upload-pack (214 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1804), reused 9929 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking connectivity... done.
Checking out files: 100% (10144/10144), done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0  2214k      0  0:00:10  0:00:10 --:--:-- 4290k
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
Package nss was not found in the pkg-config search path.
Perhaps you should add the directory containing `nss.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nss' found
gyp: Call to 'pkg-config --cflags nss' returned exit status 1.
ERROR: 1 null 

action_before_build.target.mk:13: recipe for target '/dev/null' failed
make: *** [/dev/null] Error 255
make: Leaving directory '/home/xenyou/hoge/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/xenyou/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-29-generic
gyp ERR! command "node" "/home/xenyou/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xenyou/hoge/node_modules/wrtc
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! wrtc@0.0.49 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.49 install script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-29-generic
npm ERR! command "/home/xenyou/.nvm/v0.10.36/bin/node" "/home/xenyou/.nvm/v0.10.36/bin/npm" "install" "wrtc"
npm ERR! cwd /home/xenyou/hoge
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by modeswitch** [comment]
Are you missing `libnss3-dev`?

**Comment by xenyou** [comment]
I'm very sorry. You're right.
I'll close it.
