### ISSUE TITLE
0.0.56 fails to install on node 0.12, ubuntu 12.04

### ISSUE THREAD

**Issue by feross** [node-webrtc/node-webrtc#212]
v0.0.56 started failing to install on node 0.12 and ubuntu 12.04. This is a new issue – because v0.0.55 worked just fine.
- [Install log for v0.0.56 (failure)](https://api.travis-ci.org/jobs/66984659/log.txt?deansi=true)
- [Install log for v0.0.55 (success)](https://api.travis-ci.org/jobs/66985498/log.txt?deansi=true)

Here's the whole log for the failing v0.0.56 case, in case the link stops working at some point:

```
Using worker: worker-linux-85ee80ed-2.bb.travis-ci.org:travis-linux-2

Build system information
Build language: node_js
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:    12.04
Codename:   precise
Linux Version
2.6.32-042stab090.5
Cookbooks Version
23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=master git://github.com/feross/webtorrent-hybrid.git feross/webtorrent-hybrid
Cloning into 'feross/webtorrent-hybrid'...
remote: Counting objects: 81, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 81 (delta 0), reused 6 (delta 0), pack-reused 72
Receiving objects: 100% (81/81), 9.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (37/37), done.
Checking connectivity... done.
$ cd feross/webtorrent-hybrid
$ git checkout -qf c83412ef0c0b7157f80d7687828ddb9e49c721a9
$ nvm install 0.12
######################################################################## 100.0%
Now using node v0.12.4
$ node --version
v0.12.4
$ npm --version
2.10.1
$ nvm --version
0.23.3
$ npm install 
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.12.4","npm":"2.10.1"})

> utf-8-validate@1.1.0 install /home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.1.0 install /home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil/build'

> dtrace-provider@0.4.0 install /home/travis/build/feross/webtorrent-hybrid/node_modules/webtorrent/node_modules/chromecast-js/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> wrtc@0.0.56 install /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (207 bytes)
POST git-upload-pack (216 bytes)
remote: Counting objects: 866, done
remote: Finding sources: 100% (866/866)
remote: Total 866 (delta 82), reused 458 (delta 82)
Receiving objects: 100% (866/866), 2.86 MiB | 0 bytes/s, done.
Resolving deltas: 100% (82/82), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (207 bytes)
POST git-upload-pack (216 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1804), reused 9928 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 17.04 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking connectivity... done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0  39.4M      0 --:--:-- --:--:-- --:--:-- 43.2M
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
Package nss was not found in the pkg-config search path.
Perhaps you should add the directory containing `nss.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nss' found
gyp: Call to 'pkg-config --cflags nss' returned exit status 1.
ERROR: 1 null 

make: *** [/dev/null] Error 255
make: Leaving directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab090.5
gyp ERR! command "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64"
gyp ERR! cwd /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v0.12.4/bin/node /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/versions/node/v0.12.4/bin/node /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64' (1)
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
npm ERR! Linux 2.6.32-042stab090.5
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.56 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.56 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/feross/webtorrent-hybrid/npm-debug.log

The command "eval npm install " failed. Retrying, 2 of 3.


> wrtc@0.0.56 install /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (207 bytes)
POST git-upload-pack (216 bytes)
remote: Counting objects: 866, done
remote: Finding sources: 100% (866/866)
remote: Total 866 (delta 82), reused 458 (delta 82)
Receiving objects: 100% (866/866), 2.86 MiB | 4.09 MiB/s, done.
Resolving deltas: 100% (82/82), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (207 bytes)
POST git-upload-pack (216 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1804), reused 9928 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 16.82 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking connectivity... done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0  29.0M      0 --:--:-- --:--:-- --:--:-- 31.2M
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
Package nss was not found in the pkg-config search path.
Perhaps you should add the directory containing `nss.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nss' found
gyp: Call to 'pkg-config --cflags nss' returned exit status 1.
ERROR: 1 null 

make: *** [/dev/null] Error 255
make: Leaving directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab090.5
gyp ERR! command "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64"
gyp ERR! cwd /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v0.12.4/bin/node /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/versions/node/v0.12.4/bin/node /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64' (1)
npm ERR! Linux 2.6.32-042stab090.5
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.56 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.56 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/feross/webtorrent-hybrid/npm-debug.log

The command "eval npm install " failed. Retrying, 3 of 3.


> wrtc@0.0.56 install /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (207 bytes)
POST git-upload-pack (216 bytes)
remote: Counting objects: 866, done
remote: Finding sources: 100% (866/866)
remote: Total 866 (delta 82), reused 458 (delta 82)
Receiving objects: 100% (866/866), 2.86 MiB | 0 bytes/s, done.
Resolving deltas: 100% (82/82), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (207 bytes)
POST git-upload-pack (216 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1804), reused 9928 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 17.09 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking connectivity... done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0  43.4M      0 --:--:-- --:--:-- --:--:-- 48.2M
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
Package nss was not found in the pkg-config search path.
Perhaps you should add the directory containing `nss.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nss' found
gyp: Call to 'pkg-config --cflags nss' returned exit status 1.
ERROR: 1 null 

make: *** [/dev/null] Error 255
make: Leaving directory `/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab090.5
gyp ERR! command "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64"
gyp ERR! cwd /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/travis/.nvm/versions/node/v0.12.4/bin/node /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/home/travis/.nvm/versions/node/v0.12.4/bin/node /home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/travis/build/feross/webtorrent-hybrid/node_modules/wrtc/build/wrtc/v0.0.56/Release/node-v14-linux-x64' (1)
npm ERR! Linux 2.6.32-042stab090.5
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.56 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.56 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/feross/webtorrent-hybrid/npm-debug.log

The command "eval npm install " failed 3 times.


The command "npm install " failed and exited with 1 during .

Your build has been stopped.
```

**Comment by modeswitch** [comment]
```
Package nss was not found in the pkg-config search path.
Perhaps you should add the directory containing `nss.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nss' found
gyp: Call to 'pkg-config --cflags nss' returned exit status 1.
```

You need to have `libnss` installed.
