### ISSUE TITLE
Dockerfile failing to build

### ISSUE THREAD

**Issue by omphalos** [node-webrtc/node-webrtc#228]
Running this command in develop:

```
docker build --tag wrtc .
```

Fails with these errors:

```
Updating projects from gyp files...
: Building libwebrtc ...
ninja: Entering directory `out/Release'
[1/621] CC obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_error.o
[2/621] CC obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.mode_wrappers.o
[3/621] CC obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o
[4/621] CC obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bitstr.o
[5/621] CC obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o
[6/621] CC obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bytes.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_error.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/wrtc/third_party/libwebrtc/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/dh/dh_error.c -o obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_error.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: "(" unexpected
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.mode_wrappers.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/wrtc/third_party/libwebrtc/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/aes/mode_wrappers.c -o obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.mode_wrappers.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: "(" unexpected
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bytes.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/wrtc/third_party/libwebrtc/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/asn1/a_bytes.c -o obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bytes.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: "(" unexpected
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/wrtc/third_party/libwebrtc/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/asn1/a_bool.c -o obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: "(" unexpected
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/wrtc/third_party/libwebrtc/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/aes/aes.c -o obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: "(" unexpected
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bitstr.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/wrtc/third_party/libwebrtc/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/asn1/a_bitstr.c -o obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bitstr.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: "(" unexpected
ninja: build stopped: subcommand failed.
ERROR: 1 null

make: *** [/dev/null] Error 255
make: Leaving directory `/wrtc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/wrtc/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.18.5-tinycore64
gyp ERR! command "/usr/bin/nodejs" "/wrtc/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/wrtc/build/wrtc/v0.0.58/Release/node-v11-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/wrtc/build/wrtc/v0.0.58/Release/node-v11-linux-x64"
gyp ERR! cwd /wrtc
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/wrtc/build/wrtc/v0.0.58/Release/node-v11-linux-x64/wrtc.node --module_name=wrtc --module_path=/wrtc/build/wrtc/v0.0.58/Release/node-v11-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.18.5-tinycore64
node-pre-gyp ERR! command "node" "/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /wrtc
node-pre-gyp ERR! node -v v0.10.37
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /wrtc/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/wrtc/build/wrtc/v0.0.58/Release/node-v11-linux-x64/wrtc.node --module_name=wrtc --module_path=/wrtc/build/wrtc/v0.0.58/Release/node-v11-linux-x64' (1)
INFO[0069] The command [/bin/sh -c npm install && node_modules/.bin/node-pre-gyp install --fallback-to-build] returned a non-zero code: 1
```

**Comment by omphalos** [comment]
In case someone else runs into this problem, I was able to workaround it by using the old v0.0.55 tag and [rewriting](https://gist.github.com/omphalos/895c851d372d32100aac) the Dockerfile.  This is because `node-pre-gyp` installs the prebuilt binaries in my version.  I haven't figured out how to build this from scratch though using docker, so the underlying problem remains.

**Comment by caseywebdev** [comment]
It looks like building the latest wrtc (`0.0.58`) from the `node:0.12.7` image works.

**Dockerfile**

```
FROM node:0.12.7
RUN npm install wrtc
```

**Comment by markandrus** [comment]
This does appear to work again.
