### ISSUE TITLE
build error on ubuntu

### ISSUE THREAD

**Issue by dominictarr** [node-webrtc/node-webrtc#270]
On ubuntu@15.1 & node@5.11
getting this output:

```
> npm install wrtc

> utp-native@1.2.3 install /home/dominic/c/experiments/node_modules/utp-native
> prebuild --install


> wrtc@0.0.59 install /home/dominic/c/experiments/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.59/Release/node-v47-linux-ia32.tar.gz
node-pre-gyp http 404 https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.59/Release/node-v47-linux-ia32.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.59/Release/node-v47-linux-ia32.tar.gz (falling back to source compile with node-gyp) 
gyp http GET https://nodejs.org/dist/v5.11.1/node-v5.11.1-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v5.11.1/node-v5.11.1-headers.tar.gz
gyp http GET https://nodejs.org/dist/v5.11.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v5.11.1/SHASUMS256.txt
make: Entering directory '/home/dominic/c/experiments/node_modules/wrtc/build'
make: Warning: File '/dev/null' has modification time 1274 s in the future
  ACTION Run build script /dev/null
TARGET_ARCH=ia32 PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (155 bytes)
POST git-upload-pack (164 bytes)
remote: Counting objects: 1013, done
remote: Finding sources: 100% (1013/1013)
remote: Total 1013 (delta 127), reused 552 (delta 127)
Receiving objects: 100% (1013/1013), 3.06 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (127/127), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (155 bytes)
POST git-upload-pack (164 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1803), reused 9938 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.22 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (1803/1803), done.
Checking connectivity... done.
Checking out files: 100% (10144/10144), done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0   903k      0  0:00:26  0:00:26 --:--:-- 1591k
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
: Building libwebrtc ... 
ninja: Entering directory `out/Release'
[0/616] CC obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_a[0/616] CC obj/chromium/src/third_party/boringssl/src/crypto/boringssl.crypto_[0/616] CC obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes[0/616] CXX obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncp[0/616] CXX obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncp[0/616] CC obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_[1/616] CC obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_asn1.o
FAILED: obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_asn1.o 
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_asn1.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -D_POSIX_C_SOURCE=200909L -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /home/dominic/c/experiments/node_modules/wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/dh/dh_asn1.c -o obj/chromium/src/third_party/boringssl/src/crypto/dh/boringssl.dh_asn1.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: ")" unexpected
[2/616] CXX obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_value.o
FAILED: obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_value.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_value.o.d -DV8_DEPRECATION_WARNINGS -DJSON_USE_EXCEPTION=0 -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/jsoncpp/overrides/include -I../../chromium/src/third_party/jsoncpp/source/include -I../../chromium/src/third_party/jsoncpp/source/src/lib_json -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /home/dominic/c/experiments/node_modules/wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-deprecated  -c ../../chromium/src/third_party/jsoncpp/overrides/src/lib_json/json_value.cpp -o obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_value.o
../../third_party/llvm-build/Release+Asserts/bin/clang++: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang++: Syntax error: ")" unexpected
[3/616] CC obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o
FAILED: obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o 
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -D_POSIX_C_SOURCE=200909L -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /home/dominic/c/experiments/node_modules/wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/aes/aes.c -o obj/chromium/src/third_party/boringssl/src/crypto/aes/boringssl.aes.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: ")" unexpected
[4/616] CC obj/chromium/src/third_party/boringssl/src/crypto/boringssl.crypto_error.o
FAILED: obj/chromium/src/third_party/boringssl/src/crypto/boringssl.crypto_error.o 
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/boringssl.crypto_error.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -D_POSIX_C_SOURCE=200909L -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /home/dominic/c/experiments/node_modules/wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/crypto_error.c -o obj/chromium/src/third_party/boringssl/src/crypto/boringssl.crypto_error.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: ")" unexpected
[5/616] CXX obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_reader.o
FAILED: obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_reader.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_reader.o.d -DV8_DEPRECATION_WARNINGS -DJSON_USE_EXCEPTION=0 -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/jsoncpp/overrides/include -I../../chromium/src/third_party/jsoncpp/source/include -I../../chromium/src/third_party/jsoncpp/source/src/lib_json -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /home/dominic/c/experiments/node_modules/wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-deprecated  -c ../../chromium/src/third_party/jsoncpp/overrides/src/lib_json/json_reader.cpp -o obj/chromium/src/third_party/jsoncpp/overrides/src/lib_json/jsoncpp.json_reader.o
../../third_party/llvm-build/Release+Asserts/bin/clang++: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang++: Syntax error: ")" unexpected
[6/616] CC obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o
FAILED: obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o 
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -D_POSIX_C_SOURCE=200909L -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DUSE_GLIB=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../chromium/src/third_party/boringssl/src/include -I../../chromium/src/third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /home/dominic/c/experiments/node_modules/wrtc/third_party/libwebrtc/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-format -Wno-unused-result -msse2 -mfpmath=sse -mmmx -m32 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables   -c ../../chromium/src/third_party/boringssl/src/crypto/asn1/a_bool.c -o obj/chromium/src/third_party/boringssl/src/crypto/asn1/boringssl.a_bool.o
../../third_party/llvm-build/Release+Asserts/bin/clang: 1: ../../third_party/llvm-build/Release+Asserts/bin/clang: Syntax error: ")" unexpected
ninja: build stopped: subcommand failed.
ERROR: 1 null 

action_before_build.target.mk:13: recipe for target '/dev/null' failed
make: *** [/dev/null] Error 255
make: Leaving directory '/home/dominic/c/experiments/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dominic/c/experiments/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-22-generic
gyp ERR! command "/home/dominic/.nvm/versions/node/v5.11.1/bin/node" "/home/dominic/c/experiments/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32/wrtc.node" "--module_name=wrtc" "--module_path=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32"
gyp ERR! cwd /home/dominic/c/experiments/node_modules/wrtc
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/dominic/.nvm/versions/node/v5.11.1/bin/node /home/dominic/c/experiments/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32/wrtc.node --module_name=wrtc --module_path=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/dominic/c/experiments/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.2.0-22-generic
node-pre-gyp ERR! command "/home/dominic/.nvm/versions/node/v5.11.1/bin/node" "/home/dominic/c/experiments/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/dominic/c/experiments/node_modules/wrtc
node-pre-gyp ERR! node -v v5.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/home/dominic/.nvm/versions/node/v5.11.1/bin/node /home/dominic/c/experiments/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32/wrtc.node --module_name=wrtc --module_path=/home/dominic/c/experiments/node_modules/wrtc/build/wrtc/v0.0.59/Release/node-v47-linux-ia32' (1)
/home/dominic/c/experiments
├── base32@0.0.6 
├── d64@1.0.0 
├── diff@2.2.1 
├── microcache@1.0.0 
├── pull-defer@0.2.2 
├── pull-file@0.5.0 
├── pull-fs@1.1.4 
├── pull-glob@1.0.1 
├── pull-paramap@1.1.3 
├── pull-peek@0.0.0 
├── pull-stream@3.1.0 
├── pull-write-file@0.0.1 
├── stream-to-pull-stream@1.6.6 
├── tar-fs@1.10.0 
├── textdiff-create@1.0.3 
├── through@2.3.8 
└── utp-native@1.2.3 

npm WARN enoent ENOENT: no such file or directory, open '/home/dominic/c/experiments/package.json'
npm WARN experiments No description
npm WARN experiments No repository field.
npm WARN experiments No README data
npm WARN experiments No license field.
npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/home/dominic/.nvm/versions/node/v5.11.1/bin/node" "/home/dominic/.nvm/versions/node/v5.11.1/bin/npm" "install" "wrtc"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.59 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.59 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wrtc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dominic/c/experiments/npm-debug.log
```

looks like we are getting a few `/bin/clang: Syntax error: ")" unexpected` which seems very wrong

**Comment by markandrus** [comment]
Hey @dominictarr this appears to be a (very strange) build error with WebRTC ([libwebrtc](https://github.com/js-platform/libwebrtc), specifically). I am looking into separating out and pre-compiling WebRTC binaries for future releases. Hopefully this helps issues like this.

**Comment by markandrus** [comment]
This appears to be very similar to #239. Let's track on that ticket.
