### ISSUE TITLE
NPMs 0.0.61+ cannot run in docker

### ISSUE THREAD

**Issue by trevj** [node-webrtc/node-webrtc#290]
I want to benchmark wrtc's throughput in the presence of high latency (200ms+) between peers. My preferred approach is to container-ise my test script(s) and simulate latency with `netem`.

NPM 0.0.60 runs just great in Docker:

``` bash
docker run -ti node:4.5 /bin/bash
cd /
npm install wrtc@0.0.60
cd node_modules/wrtc/
node examples/ping-pong-test.js
pc1: create offer
pc1: set local description
pc2: set remote description
pc2: create answer
pc2: set local description
pc1: set remote description
waiting
pc1: data channel open
pc2: data channel open
dc2: sending 'ping'
dc1: received 'ping'
dc1: sending 'pong'
dc2: received 'pong'
...
...
```

With 0.0.61, however, there's no output - the script hangs.

**Comment by trevj** [comment]
`strace` doesn't tell me much:

``` bash
docker run -ti --privileged node:4.5 /bin/bash
<repeat previous steps to install wrtc and run ping-pong-test>
...
...
...
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
read(3, "*", 1)                         = 1
write(7, "\250u=\2\0\0\0\0\v\0\0\0\0\0\0\0", 16) = 16
write(4, "*", 1)                        = 1
rt_sigreturn()                          = 140728427085168
...
...
...
```

Those last five lines repeat forever.

**Comment by jpevarnek** [comment]
Hey there!  Just to add a bit more information here, this ends up failing when trying to call `CreatePeerConnection` because the factory variable is set to null.  It looks to me like there are some cases where WebRTC will return null from `CreatePeerConnectionFactory`.

@markandrus I don't have much experience working with the WebRTC library directly, any chance you have some idea on what could have changed between the constructors?  Thanks!

**Comment by markandrus** [comment]
Hi @jpevarnek sounds like you hit #285. PR #287 may improve the situation, but I still have some items to address there. I hope to pick this work up again soon. Some clear betterments would be to expose the debug logging from WebRTC directly as well as fail loudly when this pointer is null.

**Comment by jpevarnek** [comment]
Definitely seems like part of that.

For what it's worth, getting:

```
(common.cc:59): ../../webrtc/base/thread.cc(194): ASSERT FAILED: owned_ @ Start
node: ../src/binding.cc:28: void setup(rtc::Thread*, rtc::Thread*): Assertion `result' failed.
Aborted (core dumped)
```

Backtrace if helpful:

```
#0  0x00007ffff6fa079b in raise (sig=5) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
#1  0x00007fffe6c00892 in rtc::Break() () from /docker-stuff/node-webrtc/build/wrtc/v0.0.62/Debug/node-v48-linux-x64/wrtc.node
#2  0x00007fffe6ab4d92 in rtc::Assert(bool, char const*, char const*, int, char const*) ()
   from /docker-stuff/node-webrtc/build/wrtc/v0.0.62/Debug/node-v48-linux-x64/wrtc.node
#3  0x00007fffe6c2e29c in rtc::Thread::Start(rtc::Runnable*) ()
   from /docker-stuff/node-webrtc/build/wrtc/v0.0.62/Debug/node-v48-linux-x64/wrtc.node
#4  0x00007fffe6972443 in setup (signalingThread=0x7fffe7ff8140 <signalingThread>, workerThread=0x7fffe7ff8380 <workerThread>)
    at ../src/binding.cc:27
#5  0x00007fffe69724f0 in init (exports=...) at ../src/binding.cc:43
#6  0x00000000010a6025 in node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) ()
#7  0x0000000000994222 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#8  0x00000000009f21d2 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) ()
#9  0x00000000009f284e in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
```

when using a debug build of WebRTC as well, probably somewhat related.
