### ISSUE TITLE
Unable to build on node 7.3.0

### ISSUE THREAD

**Issue by caseywebdev** [node-webrtc/node-webrtc#299]
Using the official node:7.3.0 docker image, I get an error while trying to build webrtc:

```
npm info lifecycle wrtc@0.0.61~install: wrtc@0.0.61

> wrtc@0.0.61 install /code/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@7.3.0 | linux | x64
node-pre-gyp info check checked for "/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64/wrtc.node" (not found)
node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v51-linux-x64.tar.gz
node-pre-gyp http 404 https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for wrtc@0.0.61 and node@7.3.0 (node-v51 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v51-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.3.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.3.0 | linux | x64
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Cannot read property 'length' of undefined
gyp ERR! stack     at parse (/code/node_modules/semver/semver.js:239:14)
gyp ERR! stack     at Function.valid (/code/node_modules/semver/semver.js:255:11)
gyp ERR! stack     at processRelease (/code/node_modules/node-gyp/lib/process-release.js:16:25)
gyp ERR! stack     at configure (/code/node_modules/node-gyp/lib/configure.js:35:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/code/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/code/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/code/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:571:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
gyp ERR! stack     at Module.load (module.js:488:32)
gyp ERR! System Linux 4.4.39-moby
gyp ERR! command "/usr/local/bin/node" "/code/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64"
gyp ERR! cwd /code/node_modules/wrtc
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /code/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64/wrtc.node --module_name=wrtc --module_path=/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/code/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.39-moby
node-pre-gyp ERR! command "/usr/local/bin/node" "/code/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /code/node_modules/wrtc
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /code/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64/wrtc.node --module_name=wrtc --module_path=/code/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64' (7)
npm info lifecycle wrtc@0.0.61~install: Failed to exec install script
```

**Comment by folkvir** [comment]
Same error on node 7.4.0 & npm 4.0.5, Ubuntu 14.04.

**Comment by caseywebdev** [comment]
Looks like it built successfully in the `node:7.6.0` image with a few deprecation warnings:

```
  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/wrtc/src/binding.o
  CXX(target) Release/obj.target/wrtc/src/create-answer-observer.o
  CXX(target) Release/obj.target/wrtc/src/create-offer-observer.o
  CXX(target) Release/obj.target/wrtc/src/datachannel.o
  CXX(target) Release/obj.target/wrtc/src/peerconnection.o
../src/peerconnection.cc: In static member function 'static void node_webrtc::PeerConnection::Run(uv_async_t*, int)':
../src/peerconnection.cc:128:78: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/7.6.0/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       argv[0] = Nan::New(RTCStatsResponse::constructor)->NewInstance(1, cargv);
                                                                              ^
../src/peerconnection.cc:176:81: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/7.6.0/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Value> dc = Nan::New(DataChannel::constructor)->NewInstance(1, cargv);
                                                                                 ^
../src/peerconnection.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE node_webrtc::PeerConnection::CreateDataChannel(Nan::NAN_METHOD_ARGS_TYPE)':
../src/peerconnection.cc:398:77: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/7.6.0/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
   Local<Value> dc = Nan::New(DataChannel::constructor)->NewInstance(1, cargv);
                                                                             ^
  CXX(target) Release/obj.target/wrtc/src/rtcstatsreport.o
  CXX(target) Release/obj.target/wrtc/src/rtcstatsresponse.o
../src/rtcstatsresponse.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE node_webrtc::RTCStatsResponse::result(Nan::NAN_METHOD_ARGS_TYPE)':
../src/rtcstatsresponse.cc:47:80: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/7.6.0/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
     reports->Set(i, Nan::New(RTCStatsReport::constructor)->NewInstance(1, cargv));
                                                                                ^
  CXX(target) Release/obj.target/wrtc/src/set-local-description-observer.o
  CXX(target) Release/obj.target/wrtc/src/set-remote-description-observer.o
  CXX(target) Release/obj.target/wrtc/src/stats-observer.o
  SOLINK_MODULE(target) Release/obj.target/wrtc.node
  COPY Release/wrtc.node
  COPY /node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v51-linux-x64/wrtc.node
  TOUCH Release/obj.target/action_after_build.stamp
```

**Comment by caseywebdev** [comment]
Looks like `npm install wrtc` on its own works fine in node 7, but there's another dependency in my package.json that, when installed first, causes the initial error during the `wrtc` build. I'll try to hunt down the exact package conflict and report back.
