### ISSUE TITLE
Install failed on Termux on Android 5.1

### ISSUE THREAD

**Issue by pboymt** [node-webrtc/node-webrtc#367]
The environment is Node.js on Termux on Android5.1.

The error code is:
```bash
$ npm i wrtc

> wrtc@0.0.67 install /data/data/com.termux/files/home/PeerProxy/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.67/Release/node-v59-android-arm.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/data/data/com.termux/files/home/PeerProxy/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:185:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/data/data/com.termux/files/home/PeerProxy/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:180:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:444:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:180:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:269:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:256:11)
node-pre-gyp ERR! System Linux 3.4.0-perf-g9b728b6-00672-g9c78db9
node-pre-gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/PeerProxy/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/PeerProxy/node_modules/wrtc
node-pre-gyp ERR! node -v v9.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.67/Release/node-v59-android-arm.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure
-- The C compiler identification is Clang 5.0.1
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Attempting to download WebRTC libraries and headers for platform "android" and architecture "arm" from

  https://github.com/aisouard/libwebrtc/releases/download/v1.0.0/libwebrtc-1.0.0-android-arm.tar.gz

Binaries unavailable!
-- Downloading: https://nodejs.org/download/release/v9.8.0/SHASUMS256.txt
CMake Error at NodeJS.cmake:293 (message):
  Unable to extract header archive checksum
Call Stack (most recent call first):
  CMakeLists.txt:12 (nodejs_init)


-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/PeerProxy/node_modules/wrtc/build/CMakeFiles/CMakeOutput.log".
Unable to configure project
Running ncmake build
make: *** No targets specified and no makefile found.  Stop.
Build failed
Built wrtc
+ wrtc@0.0.67
updated 1 package in 83.115s

```

**Comment by markandrus** [comment]
Hi, @pboymt,

We don't build and distribute binaries for Android or ARM (we should probably add a table to our README.md explaining this). To do so, we'd also need

* Android and/or ARM builds from https://github.com/aisouard/libwebrtc
* A good CI solution for building these binaries (right now, Travis CI builds Darwin and Linux, while Appveyor builds Windows)
