### ISSUE TITLE
Windows install fail 

### ISSUE THREAD

**Issue by SiarheiBokuts** [node-webrtc/node-webrtc#411]
I try to install on windows and get this error. Can somebody help me? 

```
npm install
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> uws@9.14.0 install C:\Users\User\Downloads\node-webrtc\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> travis-multirunner@4.5.0 postinstall C:\Users\User\Downloads\node-webrtc\node_modules\travis-multirunner
> node bin/travis-sync


> wrtc@0.1.5-dev install C:\Users\User\Downloads\node-webrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.5-dev/Release/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\User\Downloads\node-webrtc\node_modules\node-pre-gyp\lib\install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:120:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\User\Downloads\node-webrtc\node_modules\request\request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:563:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:20)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\Downloads\\node-webrtc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\User\Downloads\node-webrtc
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.1.5-dev/Release/node-v57-win32-x64.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure -g "Visual Studio 14 2015 Win64"
CMake binary could not be found. Please verify your PATH.
Running ncmake build
CMake binary could not be found. Please verify your PATH.
Built wrtc
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 918 packages from 1197 contributors and audited 4106 packages in 276.596s
found 29 vulnerabilities (4 low, 21 moderate, 2 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by SiarheiBokuts** [comment]
it was my fail. I deleted cmake and now install it with property "set windows path" and all work fine. 
P.S run on node js version 6.0.0
