### ISSUE TITLE
"Unable to find native module"

### ISSUE THREAD

**Issue by yarekc** [node-webrtc/node-webrtc#439]
Cannot run it

I installed it smoothly with 

`npm install wrtc` 

Then :

I run: 
**node examples/loopback.server.js**

```
node -v
v10.11.0
```

```
uname -a
Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
```

/home/netpromo/node-webrtc-develop# node examples/loopback.server.js
/home/netpromo/node-webrtc-develop/node_modules/node-cmake/index.js:40
  if(!found) throw new Error('Unable to find native module');
             ^

Error: Unable to find native module
    at requireNativeModule (/home/netpromo/node-webrtc-develop/node_modules/node-cmake/index.js:40:20)
    at Object.<anonymous> (/home/netpromo/node-webrtc-develop/lib/binding.js:3:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/netpromo/node-webrtc-develop/lib/index.js:3:15)

**Comment by markandrus** [comment]
Please share the `npm install` log output.

**Comment by yarekc** [comment]
```
/home/netpromo# npm install wrtc

> wrtc@0.2.0 install /home/netpromo/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp WARN Using needle for node-pre-gyp https download
[wrtc] Success: "/home/netpromo/node_modules/wrtc/build/Release/wrtc.node" is installed via remote
Installed a pre-built wrtc binary
npm WARN saveError ENOENT: no such file or directory, open '/home/netpromo/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/netpromo/package.json'
npm WARN netpromo No description
npm WARN netpromo No repository field.
npm WARN netpromo No README data
npm WARN netpromo No license field.

+ wrtc@0.2.0
added 193 packages from 100 contributors and audited 461 packages in 13.404s
found 0 vulnerabilities

```

**Comment by yarekc** [comment]
I tried it all: unistall, install again
I tried different folders.
I tried install from source

Server is new, recently installed with Debian9
Node and npm are using latest versions

```

node examples/loopback.server.js
/home/netpromo/node-webrtc-develop/node_modules/node-cmake/index.js:40
  if(!found) throw new Error('Unable to find native module');
             ^

Error: Unable to find native module
    at requireNativeModule (/home/netpromo/node-webrtc-develop/node_modules/node-cmake/index.js:40:20)
    at Object.<anonymous> (/home/netpromo/node-webrtc-develop/lib/binding.js:3:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/netpromo/node-webrtc-develop/lib/index.js:3:15)
```

**Comment by yarekc** [comment]
BTW, maybe I make you lose your time and did not exactly understand the goal of node-webrtc, but from what I read, it seems that you can run a webrtc relay server: 

So user1 streams to webrtc relay server and user2 can see that stream by connecting to the relay server:
 am I right or wrong ?

(a kind of quick webrtc media server)

**Comment by markandrus** [comment]
@yarekc thanks for sharing the log output. I am confused about what you are doing, as `examples/loopback.server.js` is excluded from the NPM release. So can you please share a reproducible example or a complete git repository showing how you are consuming node-webrtc?

---

The following _should_ work:

```
$ mkdir /tmp/bar
$ cd /tmp/bar
$ git clone --branch v0.2.0 https://github.com/js-platform/node-webrtc.git
$ cd node-webrtc
$ npm install
$ node examples/loopback.server.js
```

You should then see

```
Server running at 8080
```

---

> BTW, maybe I make you lose your time and did not exactly understand the goal of node-webrtc, but from what I read, it seems that you can run a webrtc relay server:
>
> So user1 streams to webrtc relay server and user2 can see that stream by connecting to the relay server:
am I right or wrong ?
> 
> (a kind of quick webrtc media server)

That is a use case I want to enable, and there should be some limited support for that.

**Comment by yarekc** [comment]
I followed it exactly step by step:
and I got the same error:

```
root@camvoice:/tmp/bar/node-webrtc# node examples/loopback.server.js
/tmp/bar/node-webrtc/node_modules/node-cmake/index.js:40
  if(!found) throw new Error('Unable to find native module');
             ^

Error: Unable to find native module
    at requireNativeModule (/tmp/bar/node-webrtc/node_modules/node-cmake/index.js:40:20)
    at Object.<anonymous> (/tmp/bar/node-webrtc/lib/binding.js:3:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by markandrus** [comment]
Not sure what's happening, but please see [node-webrtc/node-webrtc-examples](https://github.com/node-webrtc/node-webrtc-examples) for an example NPM project that depends on node-webrtc (`wrtc`). Please try this, and if you are still having trouble, feel free to reopen.
