### ISSUE TITLE
New peer is instantly closed?

### ISSUE THREAD

**Issue by kevzettler** [node-webrtc/node-webrtc#482]
This is an overlap of https://github.com/feross/simple-peer/issues/426

I just upgraded `wrtc@0.0.66` to `wrtc@0.3.5` and this problem emerged.

```
$ yarn list simple-peer wrtc
yarn list v1.4.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ simple-peer@9.2.1
└─ wrtc@0.3.5
✨  Done in 1.26s.
$ node -v; npm -v
v8.4.0
6.4.1
```

I'm using this `wrtc` module with `simple-peer` on a Node.js server

Simple Peer throws an exception when trying to signal a newly created peer like:
```
      import wrtc from 'wrtc';

      const peer = new SimplePeer({
        wrtc,
        initiator:false,
        trickle:true,
        channelConfig:{
          ordered:false,
          maxRetransmits:0
        },
        config:{
          "iceServers":[{"url":"stun:0.0.0.0:3478"},{"url":"turn:0.0.0.0:3478"}]}
      });
      peer.signal(signalPayload);
```

Where signalPayload is
```
   { type: 'offer',
     sdp: 'v=0\r\no=- 4801352722661527119 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:u6RV\r\na=ice-pwd:KW0TbJYgnCbEx7W8NETh0DKG\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5C:DB:0B:72:03:09:03:6F:EF:17:4C:25:A5:96:9E:0E:91:85:BB:43:80:A6:12:1C:F5:52:95:ED:7F:4E:15:82\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' } }
```

```
{ Error: Error: InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
    at makeError (/Users/kev/code/crashgiants/node_modules/simple-peer/index.js:1037:13)
    at /Users/kev/code/crashgiants/node_modules/simple-peer/index.js:217:44
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ERR_SET_REMOTE_DESCRIPTION' }
```

**Comment by markandrus** [comment]
Let’s follow discussion on the simple-peer issue. If indeed it’s a wrtc issue we can reopen.
