### ISSUE TITLE
Can't run wrtc with electron. Running w/ debugger gives error, running without one just crashes without error.

### ISSUE THREAD

**Issue by KolCrooks** [node-webrtc/node-webrtc#484]
When I try and run with a debugger I get the error:
`"Cannot find module '../build/Debug/wrtc.node'", running without doesn't give`
When I don't run it with a debugger I don't get any error but it just crashes out. I tried surrounding the require with a try-catch to try and get an error but it just crashes without printing anything. I then made a npm script that runs electron and that errors out. When I go to the log file for that, this is what it says:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'electron' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle signlanguagedetect@1.0.0~preelectron: signlanguagedetect@1.0.0
6 info lifecycle signlanguagedetect@1.0.0~electron: signlanguagedetect@1.0.0
7 verbose lifecycle signlanguagedetect@1.0.0~electron: unsafe-perm in lifecycle true
8 verbose lifecycle signlanguagedetect@1.0.0~electron: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\kolcr\Desktop\signLanguageDetection\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\kolcr\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\kolcr\AppData\Local\Programs\Python\Python37\;C:\Users\kolcr\AppData\Local\Microsoft\WindowsApps;;C:\Users\kolcr\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\kolcr\AppData\Roaming\npm
9 verbose lifecycle signlanguagedetect@1.0.0~electron: CWD: C:\Users\kolcr\Desktop\signLanguageDetection
10 silly lifecycle signlanguagedetect@1.0.0~electron: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle signlanguagedetect@1.0.0~electron: Returned: code: 3228369023  signal: null
12 info lifecycle signlanguagedetect@1.0.0~electron: Failed to exec electron script
13 verbose stack Error: signlanguagedetect@1.0.0 electron: `electron .`
13 verbose stack Exit status 3228369023
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid signlanguagedetect@1.0.0
15 verbose cwd C:\Users\kolcr\Desktop\signLanguageDetection
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "electron"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3228369023
22 error signlanguagedetect@1.0.0 electron: `electron .`
22 error Exit status 3228369023
23 error Failed at the signlanguagedetect@1.0.0 electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3228369023, true ]
```
I don't know where to go from here to try and solve it myself. Some advice for how I should tackle this would be handy.

**Comment by markandrus** [comment]
There aren't any Debug builds for Windows, only Release. That's why you get the error about missing ../build/Debug/wrtc.node. I couldn't get Debug builds building in AppVeyor, but if you or someone else can figure it out, I'm happy to add them.

As far as Electron, as of v0.4.0-beta1, node-webrtc should no longer require recompilation to use with Electron (I've tested Electron 5.x on all platforms and Electron 4.x on macOS). You can just `npm install` and use the prebuilt binaries. Maybe that can help your problem?

**Comment by markandrus** [comment]
Closing due to inactivity.
