### ISSUE TITLE
RTCVideoSource exits program on node-alpine without throwing error

### ISSUE THREAD

**Issue by Khauri** [node-webrtc/node-webrtc#556]
On Docker in Alpine 3.9, calling `new wrtc.nonstandard.RTCVideoSource()` silently crashes the program without throwing any errors. No code after this line is executed. 

I've made a simple example repository: https://github.com/Khauri/docker-alpine-wrtc-issue

The example uses yarn, but it didn't seem to make a difference whether yarn or npm was used. 

Is alpine missing something required for this module to work? 

My PC: macOS Mojave 10.14.2
Docker version 18.09.2, build 6247962
Base Image: `node:12.10-alpine`
Node Version: `v12.10.0`

**Comment by markandrus** [comment]
Can you please retry with a debug build? Any log messages in that case? Instructions for debug builds should be in the README.md.

**Comment by Khauri** [comment]
The behavior with the debug build seems to be inconsistent. The first two times I started the container the program crashed and the log seemed to stop at different lines. Every time after that the debug build did not crash the script. I haven't found a way to consistently get it to crash the debug build.

The release build still appears to consistently crash every time.

When testing with:
```js
const wrtc = require('wrtc')
console.log('Log 1')
new wrtc.nonstandard.RTCVideoSource()
console.log('Log 2')
```

<details>
<summary>Shortest log when the debug build crashed</summary>

```
Log 1
(audio_processing_impl.cc:421): Capture analyzer activated: 0
Capture post processor activated: 0
Render pre processor activated: 0
(webrtc_video_engine.cc:460): WebRtcVideoEngine::WebRtcVideoEngine()
(webrtc_voice_engine.cc:194): WebRtcVoiceEngine::WebRtcVoiceEngine
(webrtc_voice_engine.cc:217): WebRtcVoiceEngine::Init
(webrtc_voice_engine.cc:224): Supported send codecs in order of preference:
(webrtc_voice_engine.cc:227): opus/48000/2 { minptime=10 useinbandfec=1 } (111)
(webrtc_voice_engine.cc:227): ISAC/16000/1 (103)
(webrtc_voice_engine.cc:227): ISAC/32000/1 (104)
(webrtc_voice_engine.cc:227): G722/8000/1 (9)
(webrtc_voice_engine.cc:227): ILBC/8000/1 (102)
(webrtc_voice_engine.cc:227): PCMU/8000/1 (0)
(webrtc_voice_engine.cc:227): PCMA/8000/1 (8)
(webrtc_voice_engine.cc:227): CN/32000/1 (106)
(webrtc_voice_engine.cc:227): CN/16000/1 (105)
(webrtc_voice_engine.cc:227): CN/8000/1 (13)
(webrtc_voice_engine.cc:227): telephone-event/48000/1 (110)
(webrtc_voice_engine.cc:227): telephone-event/32000/1 (112)
(webrtc_voice_engine.cc:227): telephone-event/16000/1 (113)
(webrtc_voice_engine.cc:227): telephone-event/8000/1 (126)
(webrtc_voice_engine.cc:230): Supported recv codecs in order of preference:
(webrtc_voice_engine.cc:233): opus/48000/2 { minptime=10 useinbandfec=1 } (111)
(webrtc_voice_engine.cc:233): ISAC/16000/1 (103)
(webrtc_voice_engine.cc:233): ISAC/32000/1 (104)
(webrtc_voice_engine.cc:233): G722/8000/1 (9)
(webrtc_voice_engine.cc:233): ILBC/8000/1 (102)
(webrtc_voice_engine.cc:233): PCMU/8000/1 (0)
(webrtc_voice_engine.cc:233): PCMA/8000/1 (8)
(webrtc_voice_engine.cc:233): CN/32000/1 (106)
(webrtc_voice_engine.cc:233): CN/16000/1 (105)
(webrtc_voice_engine.cc:233): CN/8000/1 (13)
(webrtc_voice_engine.cc:233): telephone-event/48000/1 (110)
(webrtc_voice_engine.cc:233): telephone-event/32000/1 (112)
(webrtc_voice_engine.cc:233): telephone-event/16000/1 (113)
(webrtc_voice_engine.cc:233): telephone-event/8000/1 (126)
(webrtc_voice_engine.cc:310): WebRtcVoiceEngine::ApplyOptions: AudioOptions {aec: 1, agc: 1, ns: 1, hf: 1, swap: 0, audio_jitter_buffer_max_packets: 200, audio_jitter_buffer_fast_accelerate: 0, audio_jitter_buffer_min_delay_ms: 0, audio_jitter_buffer_enable_rtx_handling: 0, typing: 1, experimental_agc: 0, extended_filter_aec: 0, delay_agnostic_aec: 0, experimental_ns: 0, residual_echo_detector: 1, }
```
</details>

Maybe also important but not sure:

I tried increasing docker's memory from 2GB->4GB and that did nothing.
I also ran `docker system prune -af` before testing again.

When I changed the `"start"` script to `node . && exit 0` the build will **sometimes** exit with code 139 `segmentation fault`.

After doing some research I think this might be related to the default [thread stack size in musl](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Thread-stack-size) being too small, but I'm not sure how to change that in order to test.

**Comment by itsjustbrian** [comment]
Think I'm experiencing the same/similar issue. Segfaults consistently on `new RTCPeerConnection` on the release build, and segfaults seemingly at random on the debug build. My shortest debug output was very similar to @Khauri's.
<details>
<summary>On the release build, here's the valgrind output</summary>
<p>

```bash
Thread 8 Thread 0x0x88829:
==20== Jump to the invalid address stated on the next line
==20==    at 0x7B356: ???
==20==    by 0x9116EA3: cricket::AudioOptions::ToString() const (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x92501D8: cricket::WebRtcVoiceEngine::ApplyOptions(cricket::AudioOptions const&) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x924F662: cricket::WebRtcVoiceEngine::Init() (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x91992C2: cricket::CompositeMediaEngine::Init() (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x90E5615: rtc::FunctorMessageHandler<bool, cricket::ChannelManager::Init()::$_3>::OnMessage(rtc::Message*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x91034FB: rtc::MessageQueue::Dispatch(rtc::Message*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9114397: rtc::Thread::ReceiveSendsFromThread(rtc::Thread const*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9102AF4: rtc::MessageQueue::Get(rtc::Message*, int, bool) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9113E47: rtc::Thread::Run() (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9113BA8: rtc::Thread::PreRun(void*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x405172A: ??? (in /lib/ld-musl-x86_64.so.1)
==20==  Address 0x7b356 is not stack'd, malloc'd or (recently) free'd
==20== 
==20== 
==20== Process terminating with default action of signal 11 (SIGSEGV)
==20==  Bad permissions for mapped region at address 0x7B356
==20==    at 0x7B356: ???
==20==    by 0x9116EA3: cricket::AudioOptions::ToString() const (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x92501D8: cricket::WebRtcVoiceEngine::ApplyOptions(cricket::AudioOptions const&) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x924F662: cricket::WebRtcVoiceEngine::Init() (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x91992C2: cricket::CompositeMediaEngine::Init() (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x90E5615: rtc::FunctorMessageHandler<bool, cricket::ChannelManager::Init()::$_3>::OnMessage(rtc::Message*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x91034FB: rtc::MessageQueue::Dispatch(rtc::Message*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9114397: rtc::Thread::ReceiveSendsFromThread(rtc::Thread const*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9102AF4: rtc::MessageQueue::Get(rtc::Message*, int, bool) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9113E47: rtc::Thread::Run() (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x9113BA8: rtc::Thread::PreRun(void*) (in /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
==20==    by 0x405172A: ??? (in /lib/ld-musl-x86_64.so.1)
```

</p>
</details>

<details>
<summary>And here's an attempt at a gdb backtrace</summary>
<p>

```bash
#0  0x000000000007b356 in ?? ()
#1  0x0000000009119ba2 in rtc::SimpleStringBuilder::AppendFormat(char const*, ...) ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#2  0x0000000009116ea4 in cricket::AudioOptions::ToString() const ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#3  0x00000000092501d9 in cricket::WebRtcVoiceEngine::ApplyOptions(cricket::AudioOptions const&) ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#4  0x000000000924f663 in cricket::WebRtcVoiceEngine::Init() () from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#5  0x00000000091992c3 in cricket::CompositeMediaEngine::Init() ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#6  0x00000000090e5616 in rtc::FunctorMessageHandler<bool, cricket::ChannelManager::Init()::$_3>::OnMessage(rtc::Message*)
    () from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#7  0x00000000091034fc in rtc::MessageQueue::Dispatch(rtc::Message*) ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#8  0x0000000009114398 in rtc::Thread::ReceiveSendsFromThread(rtc::Thread const*) ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#9  0x0000000009102af5 in rtc::MessageQueue::Get(rtc::Message*, int, bool) ()
   from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#10 0x0000000009113e48 in rtc::Thread::Run() () from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#11 0x0000000009113ba9 in rtc::Thread::PreRun(void*) () from /usr/src/app/node_modules/wrtc/build/Release/wrtc.node
#12 0x000000000405172b in ?? () from /lib/ld-musl-x86_64.so.1
#13 0x0000000000000000 in ?? ()
```

</p>
</details>

Neither seem really eye-opening. This stuff isn't my forte so apologies if I did it incorrectly.
I also have to agree with @Khauri that based on what I've seen it's probably related to musl, since the problem only happens on alpine. And other issues online related to musl and segfaults are usually because of the thread stack size issue.

**Comment by markandrus** [comment]
Thanks for digging into this, y'all. I also don't know a lot about musl or the potential stack size issue. I'm marking this as "help-wanted" as I probably won't be able to dig into this any time soon, but I welcome PRs.
