### ISSUE TITLE
Build Failure on MacOS 10.15 with Node 12.12

### ISSUE THREAD

**Issue by taylorhoward92** [node-webrtc/node-webrtc#577]
I'm trying to build on MacOS and getting the error below. The whole folder `external/libwebrtc/build/Release` is empty at this point.
Possibly related to #477 but the solution isn't provided in detail there so I'm not really sure what to do.

```bash
ninja: error: 'external/libwebrtc/build/Release/obj/buildtools/third_party/libc++/libc++/algorithm.o', needed by 'Release/wrtc.node', missing and no known rule to make it
```

<details>
<summary>Full log</summary>

```bash
~/Development 
➜ system_profiler SPSoftwareDataType      
Software:

    System Software Overview:

      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Taylor’s MacBook Pro
      User Name: Taylor Howard (taylorhoward)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 23:55


~/Development 
➜ git --version                   
git version 2.23.0

~/Development 
➜ cmake --version                   
cmake version 3.15.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

~/Development 
➜ system_profiler SPDeveloperToolsDataType
Developer:

    Developer Tools:

      Version: 11.2.1 (11B500)
      Location: /Applications/Xcode.app
      Applications:
          Xcode: 11.2.1 (15526.1)
          Instruments: 11.2.1 (64531.4)
      SDKs:
          iOS:
              13.2: (17B102)
          iOS Simulator:
              13.2: (17B102)
          macOS:
              10.15: (19B89)
              19.0: 
          tvOS:
              13.2: (17K90)
          tvOS Simulator:
              13.2: (17K90)
          watchOS:
              6.1: (17S80)
          watchOS Simulator:
              6.1: (17S80)


~/Development 
➜ fetch --help
usage: fetch.py [options] <config> [--property=value [--property2=value2 ...]]

This script can be used to download the Chromium sources. See
http://www.chromium.org/developers/how-tos/get-the-code
for full usage instructions.

Valid options:
   -h, --help, help   Print this message.
   --nohooks          Don't run hooks after checkout.
   --force            (dangerous) Don't look for existing .gclient file.
   -n, --dry-run      Don't run commands, only print them.
   --no-history       Perform shallow clones, don't fetch the full git history.

Valid fetch configs:
  android
  android_internal
  breakpad
  chromium
  config_util
  crashpad
  dart
  depot_tools
  devtools-frontend
  goma_client
  gyp
  infra
  infra_internal
  inspector_protocol
  ios
  ios_internal
  nacl
  naclports
  node-ci
  pdfium
  skia
  skia_buildbot
  syzygy
  v8
  webrtc
  webrtc_android
  webrtc_ios

~/Development 
➜ git clone https://github.com/node-webrtc/node-webrtc.git
Cloning into 'node-webrtc'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 7235 (delta 6), reused 13 (delta 4), pack-reused 7210
Receiving objects: 100% (7235/7235), 7.17 MiB | 254.00 KiB/s, done.
Resolving deltas: 100% (5015/5015), done.

~/Development took 33s 
➜ cd node-webrtc

node-webrtc on  develop is 📦 v0.4.3-dev via ⬢ v12.12.0 
➜ SKIP_DOWNLOAD=true npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> fsevents@1.2.9 install /Users/taylorhoward/Development/node-webrtc/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/taylorhoward/Development/node-webrtc/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> core-js@2.6.10 postinstall /Users/taylorhoward/Development/node-webrtc/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> travis-multirunner@4.5.0 postinstall /Users/taylorhoward/Development/node-webrtc/node_modules/travis-multirunner
> node bin/travis-sync


> wrtc@0.4.3-dev install /Users/taylorhoward/Development/node-webrtc
> node scripts/download-prebuilt-or-build-from-source.js

Running ncmake configure
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/local/bin/git (found version "2.23.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Downloading: https://nodejs.org/download/release/v12.12.0/SHASUMS256.txt
* Closing connection 0
-- NodeJS: Using node, version v12.12.0
-- Downloading: https://nodejs.org/download/release/v12.12.0/node-v12.12.0-headers.tar.gz
* Closing connection 0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/taylorhoward/Development/node-webrtc/build
Running ncmake build
ninja: error: 'external/libwebrtc/build/Release/obj/buildtools/third_party/libc++/libc++/algorithm.o', needed by 'Release/wrtc.node', missing and no known rule to make it
Build failed
/Users/taylorhoward/Development/node-webrtc/scripts/build-from-source.js:36
    throw new Error('ncmake build failed for wrtc');
    ^

Error: ncmake build failed for wrtc
    at main (/Users/taylorhoward/Development/node-webrtc/scripts/build-from-source.js:36:11)
    at main (/Users/taylorhoward/Development/node-webrtc/scripts/download-prebuilt-or-build-from-source.js:19:3)
    at Object.<anonymous> (/Users/taylorhoward/Development/node-webrtc/scripts/download-prebuilt-or-build-from-source.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.4.3-dev install: `node scripts/download-prebuilt-or-build-from-source.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.4.3-dev install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taylorhoward/.npm/_logs/2019-11-15T09_20_25_784Z-debug.log
```
</details>

**Comment by taylorhoward92** [comment]
For some reason when using `SKIP_DOWNLOAD=true npm install` and hence CMake via ncmake, the `ExternalProject_Add` clauses are not actually triggering to download dependencies. I'm making some progress running CMake manually however working through some other errors now.

```bash
git clone https://github.com/node-webrtc/node-webrtc.git
cd node-webrtc
npm install --ignore-scripts
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
cmake --build .
```

**Comment by taylorhoward92** [comment]
Duplicate of #477
