### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by nourikhalass** [node-webrtc/node-webrtc#608]
While trying to build from source under Windows (Windows 10 Home) I have encountered numerous problems. I've overcome most of them (and I want to update the build_from_source.md with my findings once this is resolved), I am now stranded with this error:
```
C:\Development\node-webrtc>npm install

> wrtc@0.4.5-dev install C:\Development\node-webrtc
> node scripts/download-prebuilt-or-build-from-source.js

Running ncmake configure -g "Visual Studio 15 2017 Win64"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- NodeJS: Using node, version v11.9.0
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Development/node-webrtc/build
Running ncmake build
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Performing update step for 'project_catch2'
  Performing update step for 'project_depot_tools'
  Creating directories for 'project_libwebrtc'
  Building Custom Rule C:/Development/node-webrtc/CMakeLists.txt
  CMake does not need to re-run because C:/Development/node-webrtc/build/CMakeFiles/generate.stamp is up-to-date.
  Performing download step for 'project_libwebrtc'
  Add depot_tools to PATH
  SET DEPOT_TOOLS_WIN_TOOLCHAIN=0
  gclient config
  Cannot rebase: You have unstaged changes.
  Please commit or stash them.
  Failed to update depot_tools.
  gclient sync
  Cannot rebase: You have unstaged changes.
  Please commit or stash them.
  Failed to update depot_tools.
  lastchange
  update toolchain
  download clang
  rmdir webrtc
  mklink /D webrtc src
  symbolic link created for webrtc <<===>> src
  No update step for 'project_libwebrtc'
  No patch step for 'project_libwebrtc'
  Performing configure step for 'project_libwebrtc'
  Add depot_tools to PATH
  SET DEPOT_TOOLS_WIN_TOOLCHAIN=0
  cd SOURCE_DIR
  gn gen BINARY_DIR "--args=GN_GEN_ARGS"
  Traceback (most recent call last):
    File "C:/Development/node-webrtc/build/external/libwebrtc/download/src/build/toolchain/win/setup_toolchain.py", line 297, in <module>
      main()
    File "C:/Development/node-webrtc/build/external/libwebrtc/download/src/build/toolchain/win/setup_toolchain.py", line 284, in main
      assert vc_lib_atlmfc_path
  AssertionError
  ERROR at //build/toolchain/win/BUILD.gn:348:24: Script returned non-zero exit code.
    win_toolchain_data = exec_script("setup_toolchain.py",
                         ^----------
  Current dir: C:/Development/node-webrtc/build/external/libwebrtc/build/Release/
  Command: C:/Development/node-webrtc/build/external/depot_tools/src/win_tools-2_7_6_bin/python/bin/python.exe C:/Development/node-webrtc/build/external/libw
  ebrtc/download/src/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2017/Community" "C:\Program Files (x86)\Windows K
  its\10" "C:\WINDOWS\Sysnative;C:\WINDOWS\SysWOW64;Arm64Unused" win x86 environment.x86
  Returned 1 and printed out:

  vc_bin_dir = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x86"
  include_flags_I = "\"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\" \
  "/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windo
  ws Kits\\10\\include\\10.0.17763.0\\ucrt\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared\" \"/I..\\.
  .\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits
  \\10\\include\\10.0.17763.0\\winrt\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\cppwinrt\" \"/I..\\..\\.
  .\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\" \"/I..\\..\\..\\..\\..\\..\\..\\P
  rogram Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\atlmfc\\include\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files
   (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\VS\\include\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Inclu
  de\\10.0.17763.0\\ucrt\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\VS\\UnitTest\\includ
  e\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\um\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\
  \Windows Kits\\10\\Include\\10.0.17763.0\\shared\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\winrt\" \"
  /I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\cppwinrt\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\
  \Windows Kits\\NETFXSDK\\4.6.1\\Include\\um\" \"/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\Include\\um\""
  include_flags_imsvc = "\"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\inc
  lude\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Fi
  les (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\ucrt\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0
  \\shared\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Progr
  am Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.1
  7763.0\\cppwinrt\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include
  \" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\atlmfc\\include\" \"-im
  svc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\VS\\include\" \"-imsvc..\\..\\..\\..\\..\\..\\
  ..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\ucrt\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\
  2017\\Community\\VC\\Auxiliary\\VS\\UnitTest\\include\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\u
  m\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\shared\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program
  Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\winrt\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.1776
  3.0\\cppwinrt\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\Include\\um\" \"-imsvc..\\..\\..\\..\\..\\..\\..\\P
  rogram Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\Include\\um\""
  vc_lib_path = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x86"

  See //build/toolchain/win/BUILD.gn:401:3: whence it was called.
    win_toolchains("x86") {
    ^----------------------
  See //BUILD.gn:29:3: which caused the file to be included.
    group("default") {
    ^-----------------
  Traceback (most recent call last):
    File "C:/Development/node-webrtc/build/external/libwebrtc/download/src/build/toolchain/win/setup_toolchain.py", line 297, in <module>
      main()
    File "C:/Development/node-webrtc/build/external/libwebrtc/download/src/build/toolchain/win/setup_toolchain.py", line 284, in main
      assert vc_lib_atlmfc_path
  AssertionError
  ERRORLEVEL: 1
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited wi
th code 1. [C:\Development\node-webrtc\build\project_libwebrtc.vcxproj]
Build failed
C:\Development\node-webrtc\scripts\build-from-source.js:36
    throw new Error('ncmake build failed for wrtc');
    ^

Error: ncmake build failed for wrtc
    at main (C:\Development\node-webrtc\scripts\build-from-source.js:36:11)
    at main (C:\Development\node-webrtc\scripts\download-prebuilt-or-build-from-source.js:19:3)
    at Object.<anonymous> (C:\Development\node-webrtc\scripts\download-prebuilt-or-build-from-source.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.4.5-dev install: `node scripts/download-prebuilt-or-build-from-source.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.4.5-dev install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

How do I resolve this issue?

**Comment by simizuhikari** [comment]
I had similar to you situation.  I have tried to install the Windows 10 SDK to solve it.
May be helpful.
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
