### ISSUE TITLE
Open handles with Jest test runner

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#650]
I have been using `node-webrtc` with some tests using `jest` but they didn't finish due to open handles, pointing to the internal `RTCPeerConnection` constructor at https://github.com/node-webrtc/node-webrtc/blob/5ebd50e83f265e04dab1e0410d869da2cd534d11/lib/peerconnection.js#L17. I've crafted a minimal `jest` test and was able to isolate it:

```js
test.only('open handles', function() {
  var pc = new RTCPeerConnection();

  pc.close();
});
```

```js
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  RTCPeerConnection

      70 | 
      71 | test.only('open handles', function() {
    > 72 |   var pc = new RTCPeerConnection();
         |            ^
      73 | 
      74 |   pc.close();
      75 | });

      at new RTCPeerConnection (node_modules/wrtc/lib/peerconnection.js:17:12)
      at Object.<anonymous> (__tests__/index.js:72:12)

Segmentation fault (core dumped)
```

I think this has been overseen before due to usage of `tape` test runner, while `jest` is more strict with this kind of things about open handles and the events queue, althouth is strange because I've used `node-webrtc` in the past with auto-clossing apps without problems... On the other hand, I have been getting open handlers about `MediaStreamTrack` objects from `getUserMedia()`, also after calling to their `stop()` method.

As a side note, I've been getting in the tests a `code dump` before but it was only at tests loading time and it worked when relaunching the tests, but this one after fully finished them is happening always.

Maybe I've found some hidden bugs in the object destructors? :-)

**Comment by markandrus** [comment]
> As a side note, I've been getting in the tests a code dump before but it was only at tests loading time and it worked when relaunching the tests, but this one after fully finished them is happening always.

This is a problem we need to solve. There's been some discussion in other threads.

Regarding Jest detecting open handles, it might also be due to the way we cleanup. Not sure how Jest detects the open handles, but the `close` methods are actually asynchronous: they enqueue a little task to the object's event loop to finally tear them down. It might not be until the next execution of their event loop until the handle is closed. So if Jest is expecting a synchronous closure of the handles, it doesn't work that way.

**Comment by piranna** [comment]
> Not sure how Jest detects the open handles

Jest waits for a second after tests have finished before showing the message, and if so, then checks what open handlers (net connections, timers...) are still active, and waits until they are finished. This can be usually indefinite when there's a real open handle, like is this case, so there's something on the clean-up process that's being missed. The open handlers report allways point to the C++ constructor of the internal PeerConnection object as the reason, so probably it's not fully closed or needs to call to some unregister function.
