### ISSUE TITLE
DLL Error in Linux

### ISSUE THREAD

**Issue by Harris-lans** [node-webrtc/node-webrtc#654]
Hello,

I am using this library in a microservice. Everything seems to work well on windows but I am facing this error when running the service in an Alpline Linux Docker container. The installation completes successfully, but on running in the container it throws an error. It seems to be some problem with loading the native .so file. Any help would be great. Thank you in advance. Please let me know if you need any other information.

```
internal/modules/cjs/loader.js:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/wrtc/build/Release/wrtc.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/node_modules/wrtc/lib/binding.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

**Comment by Harris-lans** [comment]
I have found the issue. I had to install the below package

```
apk add libc6-compat
ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
```

Thank you

**Comment by ghost** [comment]
Shouldn't this be documented somewhere?
