### ISSUE TITLE
Can't use as git dependency

### ISSUE THREAD

**Issue by piranna** [node-webrtc/node-webrtc#676]
When using [my fork with support for Node.js 15](https://github.com/node-webrtc/node-webrtc/pull/675) as a git dependency (setting a git repository as version field), it automatically download and compile all the libraries like `libwrtc` and `gn`, but once it tries to compile `node-webrtc` itself, I get an error about not finding the `node-addon-api` headers:

```sh
npm ERR! /home/piranna/Trabajo/Atos/awrtc_node-webrtc/node_modules/wrtc/src/binding.cc:8:10: fatal error: node-addon-api/napi.h: No existe el archivo o el directorio
npm ERR!     8 | #include <node-addon-api/napi.h>
npm ERR!       |          ^~~~~~~~~~~~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! gmake[2]: *** [CMakeFiles/wrtc.dir/build.make:63: CMakeFiles/wrtc.dir/src/binding.cc.o] Error 1
npm ERR! gmake[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/wrtc.dir/all] Error 2
npm ERR! gmake: *** [Makefile:84: all] Error 2
npm ERR! Build failed
npm ERR! /home/piranna/Trabajo/Atos/awrtc_node-webrtc/node_modules/wrtc/scripts/build-from-source.js:34
npm ERR!     throw new Error('ncmake build failed for wrtc');
npm ERR!     ^
npm ERR! 
npm ERR! Error: ncmake build failed for wrtc
npm ERR!     at main (/home/piranna/Trabajo/Atos/awrtc_node-webrtc/node_modules/wrtc/scripts/build-from-source.js:34:11)
npm ERR!     at main (/home/piranna/Trabajo/Atos/awrtc_node-webrtc/node_modules/wrtc/scripts/download-prebuilt-or-build-from-source.js:19:3)
npm ERR!     at Object.<anonymous> (/home/piranna/Trabajo/Atos/awrtc_node-webrtc/node_modules/wrtc/scripts/download-prebuilt-or-build-from-source.js:22:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:973:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47
```

I think it could be maybe an issue related to being an extra level down, since it's a dependency of a dependency.

**Comment by piranna** [comment]
I confirm that `npm install` in the project itself works, so it's an issue with the include paths when used as git dependency. It's not too much important since build time is long enough to make it impractical to use as a git dependency (2-3 hours in my machine counting with code and tools download)... but also this makes it more frustrating, that after so much time installing it crash.

**Comment by markandrus** [comment]
@piranna as I mentioned on the `engines` PR, this might actually be an issue with NPM 7 not installing dependencies at the right time. Not sure. Depending on this repo as a git dependency isn't something I usually do, so I will probably not invest time in this.

> but also this makes it more frustrating, that after so much time installing it crash.

Yes, agree. This is why I changed the project to never attempt to build from source when downloading from NPM.
