### ISSUE TITLE
install failed on windows 10 

### ISSUE THREAD

**Issue by bluelovers** [node-webrtc/node-webrtc#683]
```
T:\tmp\777>npm i wrtc
npm ERR! code 1
npm ERR! path T:\tmp\777\node_modules\wrtc
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/download-prebuilt.js
npm ERR! 'node-pre-gyp' ���O�����Υ~���R�O�B�i���檺�{���Χ
妸�ɡC

npm ERR! A complete log of this run can be found in:
npm ERR!     T:\cache\npm-cache\_logs\2021-02-13T18_33_36_150Z-debug.log

T:\tmp\777>
```

```
版本	Windows 10 企業版
版本	20H2
安裝於	‎2020/‎7/‎27
OS 組建	19042.804
體驗	Windows Feature Experience Pack 120.2212.551.0
```

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'wrtc'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\USER\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:T:\tmp\777\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\User\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\USER\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 5ef4111a54160573
20 timing npm:load Completed in 19ms
21 timing arborist:ctor Completed in 0ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 130ms
24 timing idealTree:userRequests Completed in 1ms
25 silly idealTree buildDeps
26 silly fetch manifest wrtc@*
27 http fetch GET 200 https://registry.npmjs.org/wrtc 12ms (from cache)
28 silly placeDep ROOT wrtc@0.4.7 OK for: 777@1.0.0 want: *
29 silly fetch manifest domexception@^1.0.1
30 http fetch GET 304 https://registry.npmjs.org/domexception 114ms (from cache)
31 timing idealTree:#root Completed in 133ms
32 silly placeDep ROOT domexception@1.0.1 OK for: wrtc@0.4.7 want: ^1.0.1
33 silly fetch manifest webidl-conversions@^4.0.2
34 http fetch GET 200 https://registry.npmjs.org/webidl-conversions 2ms (from cache)
35 timing idealTree:node_modules/wrtc Completed in 4ms
36 silly placeDep ROOT webidl-conversions@4.0.2 OK for: domexception@1.0.1 want: ^4.0.2
37 timing idealTree:node_modules/domexception Completed in 1ms
38 timing idealTree:node_modules/webidl-conversions Completed in 0ms
39 timing idealTree:buildDeps Completed in 140ms
40 timing idealTree:fixDepFlags Completed in 13ms
41 timing idealTree Completed in 287ms
42 timing reify:loadTrees Completed in 287ms
43 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\bcrypto' ]
44 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\leveldown' ]
45 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\gc-stats' ]
46 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\ursa-optional' ]
47 timing reify:diffTrees Completed in 2ms
48 silly reify mark retired [ 'T:\\tmp\\777\\node_modules\\bcrypto' ]
49 silly reify mark retired [ 'T:\\tmp\\777\\node_modules\\leveldown' ]
50 silly reify mark retired [ 'T:\\tmp\\777\\node_modules\\gc-stats' ]
51 silly reify mark retired [ 'T:\\tmp\\777\\node_modules\\ursa-optional' ]
52 silly reify moves {
52 silly reify   'T:\\tmp\\777\\node_modules\\bcrypto': 'T:\\tmp\\777\\node_modules\\.bcrypto-4yAcQ0cs',
52 silly reify   'T:\\tmp\\777\\node_modules\\leveldown': 'T:\\tmp\\777\\node_modules\\.leveldown-HbwbttCx',
52 silly reify   'T:\\tmp\\777\\node_modules\\gc-stats': 'T:\\tmp\\777\\node_modules\\.gc-stats-s62IVyLn',
52 silly reify   'T:\\tmp\\777\\node_modules\\ursa-optional': 'T:\\tmp\\777\\node_modules\\.ursa-optional-ZDWPeXCZ'
52 silly reify }
53 timing reify:retireShallow Completed in 6ms
54 timing reify:createSparse Completed in 1ms
55 timing reifyNode:node_modules/wrtc Completed in 25ms
56 timing arborist:ctor Completed in 0ms
57 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\bcrypto' ]
58 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\leveldown' ]
59 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\gc-stats' ]
60 silly reify mark deleted [ 'T:\\tmp\\777\\node_modules\\ursa-optional' ]
61 timing reify:diffTrees Completed in 1ms
62 timing reify:loadBundles Completed in 29ms
63 timing reifyNode:node_modules/webidl-conversions Completed in 15ms
64 timing reifyNode:node_modules/domexception Completed in 16ms
65 timing reify:unpack Completed in 16ms
66 timing reify:unretire Completed in 0ms
67 timing build:queue Completed in 1ms
68 info run wrtc@0.4.7 install node_modules/wrtc node scripts/download-prebuilt.js
69 info run wrtc@0.4.7 install { code: 1, signal: null }
70 timing reify:rollback:createSparse Completed in 5ms
71 timing reify:rollback:retireShallow Completed in 2ms
72 timing command:install Completed in 515ms
73 verbose stack Error: command failed
73 verbose stack     at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
73 verbose stack     at ChildProcess.emit (node:events:379:20)
73 verbose stack     at maybeClose (node:internal/child_process:1065:16)
73 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
74 verbose pkgid wrtc@0.4.7
75 verbose cwd T:\tmp\777
76 verbose Windows_NT 10.0.19042
77 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "wrtc"
78 verbose node v15.6.0
79 verbose npm  v7.5.4
80 error code 1
81 error path T:\tmp\777\node_modules\wrtc
82 error command failed
83 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/download-prebuilt.js
84 error 'node-pre-gyp' ���O�����Υ~���R�O�B�i���檺�{���Χ妸�ɡC
85 verbose exit 1

```

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'wrtc'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\USER\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:T:\tmp\777\.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\User\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\USER\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session cbc6ffd45190ca25
20 timing npm:load Completed in 19ms
21 timing arborist:ctor Completed in 0ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 13ms
24 timing idealTree:userRequests Completed in 2ms
25 silly idealTree buildDeps
26 silly fetch manifest wrtc@*
27 http fetch GET 304 https://registry.npmjs.org/wrtc 809ms (from cache)
28 silly placeDep ROOT wrtc@0.4.7 OK for: 777@1.0.0 want: *
29 silly fetch manifest domexception@^1.0.1
30 http fetch GET 304 https://registry.npmjs.org/domexception 38ms (from cache)
31 timing idealTree:#root Completed in 857ms
32 silly placeDep ROOT domexception@1.0.1 OK for: wrtc@0.4.7 want: ^1.0.1
33 silly fetch manifest webidl-conversions@^4.0.2
34 http fetch GET 304 https://registry.npmjs.org/webidl-conversions 27ms (from cache)
35 timing idealTree:node_modules/wrtc Completed in 30ms
36 silly placeDep ROOT webidl-conversions@4.0.2 OK for: domexception@1.0.1 want: ^4.0.2
37 timing idealTree:node_modules/domexception Completed in 1ms
38 timing idealTree:node_modules/webidl-conversions Completed in 0ms
39 timing idealTree:buildDeps Completed in 888ms
40 timing idealTree:fixDepFlags Completed in 1ms
41 timing idealTree Completed in 904ms
42 timing reify:loadTrees Completed in 905ms
43 timing reify:diffTrees Completed in 0ms
44 silly reify moves {}
45 timing reify:retireShallow Completed in 0ms
46 timing reify:createSparse Completed in 1ms
47 timing reifyNode:node_modules/wrtc Completed in 24ms
48 timing arborist:ctor Completed in 0ms
49 timing reify:diffTrees Completed in 0ms
50 timing reify:loadBundles Completed in 31ms
51 timing reifyNode:node_modules/webidl-conversions Completed in 9ms
52 timing reifyNode:node_modules/domexception Completed in 10ms
53 timing reify:unpack Completed in 10ms
54 timing reify:unretire Completed in 0ms
55 timing build:queue Completed in 1ms
56 info run wrtc@0.4.7 install node_modules/wrtc node scripts/download-prebuilt.js
57 info run wrtc@0.4.7 install { code: 1, signal: null }
58 timing reify:rollback:createSparse Completed in 6ms
59 timing reify:rollback:retireShallow Completed in 0ms
60 timing command:install Completed in 1112ms
61 verbose stack Error: command failed
61 verbose stack     at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
61 verbose stack     at ChildProcess.emit (node:events:379:20)
61 verbose stack     at maybeClose (node:internal/child_process:1065:16)
61 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
62 verbose pkgid wrtc@0.4.7
63 verbose cwd T:\tmp\777
64 verbose Windows_NT 10.0.19042
65 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "wrtc"
66 verbose node v15.6.0
67 verbose npm  v7.5.4
68 error code 1
69 error path T:\tmp\777\node_modules\wrtc
70 error command failed
71 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/download-prebuilt.js
72 error 'node-pre-gyp' ���O�����Υ~���R�O�B�i���檺�{���Χ妸�ɡC
73 verbose exit 1

```

**Comment by TheOtterlord** [comment]
got the same thing here

**Comment by rgascons** [comment]
same issue in Kali Linux
