### ISSUE TITLE
ICE gathering issue

### ISSUE THREAD

**Issue by gbfarah** [node-webrtc/node-webrtc#712]
With reference to https://github.com/node-webrtc/node-webrtc-examples/tree/master/examples/audio-video-loopback 
when adjusting  webrtconnection.js to attempt to use a stun server as below, the example actually fails with  the error below

```
    const peerConnection = new RTCPeerConnection({
      sdpSemantics: 'unified-plan',
      iceServers: [
        {
          urls: ['stun:stun.l.google.com:19302']
        }
      ]
    });
```

```
(node:46916) UnhandledPromiseRejectionWarning: Error: Timed out waiting for host candidates
    at Timeout._onTimeout (webrtcconnection.js:213:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Can I get some clarication whether node-webrtc actually performs ice candidate gathering from ICE servers... when removing iceServers from list above all the local interface candidates are found 

Also can I get some feedback on what can be done when running in a server (AWS) environment....

**Comment by gbfarah** [comment]
A bit more clarification on the above. It appears that reflective ICE gather is working  in the case where peer connection is the creator of the offer as below . It however fails to work when the peer connection is the answerer. In code below pc2 ice gathering works while pc1 does not

```

var pc = new RTCPeerConnection({
    iceServers: [
      {
        urls: ['stun:stun.l.google.com:19302']
      }
    ]
  });
var pc2 = new RTCPeerConnection({
    iceServers: [
      {
        urls: ['stun:stun.l.google.com:19302']
      }
    ]
  });

  const offer= await pc2.createOffer();
  await pc2.setLocalDescription(offer);
  
  await pc.setRemoteDescription(pc2.localDescription);
  pc.createAnswer().then(function(e) {
    pc.setLocalDescription(new RTCSessionDescription(e));
  });
```
