### ISSUE TITLE
Option to specify a Win32 version when building on Linux

### ISSUE THREAD

**Issue by kross-italk** [node-webrtc/node-webrtc#743]
I'm cross compiling for Windows on Linux using `vercel/pkg`. Is there an environment variable to specify I want the Win32 version instead of detecting it from the build OS?

A minimal example is:
A package.json with `wrtc` and `pkg`. 

app/src/index.js
```
const { RTCPeerConnection } = require( 'wrtc' );
```

Build with 
`pkg -c package.json -t node18-win`

And run the app on windows. I get this error:

```
Error: ...\wrtc\build\Release\wrtc.node is not a valid Win32 application.
```

**Comment by kross-italk** [comment]
It looks like an option could be added here: https://github.com/node-webrtc/node-webrtc/blob/develop/scripts/download-prebuilt.js#L14

**Comment by kross-italk** [comment]
Building with my branch I can get the win32 binary. Which promptly fails when run on windows. 

```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: UNEXPECTED-15
    at readFromSnapshot (pkg/prelude/bootstrap.js:942:16)
    at Object.readSync (pkg/prelude/bootstrap.js:949:12)
    at copyInChunks (pkg/prelude/bootstrap.js:175:21)
    at Object.copyFileSync (pkg/prelude/bootstrap.js:1185:5)
    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:247:12)
    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:203:9)
    at process.dlopen (pkg/prelude/bootstrap.js:2236:9)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
```
