### ISSUE TITLE
ncmake build failed for wrtc (darwin arm64)

### ISSUE THREAD

**Issue by brandonros** [node-webrtc/node-webrtc#755]
```
$ SKIP_DOWNLOAD=true npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'wrtc@0.4.7-dev',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^8.11.2 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0 || ^15.0.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v18.14.2', npm: '9.5.0' }
npm WARN EBADENGINE }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated trim@0.0.1: Use String.prototype.trim() instead
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated date-format@2.1.0: 2.x is no longer supported. Please upgrade to 4.x or higher.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated streamroller@1.0.6: 1.x is no longer supported. Please upgrade to 3.x or higher.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated log4js@4.5.1: 4.x is no longer supported. Please upgrade to 6.x or higher.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

> wrtc@0.4.7-dev install
> node scripts/download-prebuilt-or-build-from-source.js

Running ncmake configure
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Downloading: https://nodejs.org/download/release/v18.14.2/SHASUMS256.txt
-- NodeJS: Using node, version v18.14.2
-- Downloading: https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz
-- Configuring done (5.9s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/brandonros/Desktop/node-webrtc/build
Running ncmake build
[3/117] Performing download step (git clone) for 'project_depot_tools'
Cloning into 'src'...
HEAD is now at 2fddb956 [git recipe_module] Add tags flag for fetch
[11/117] Performing download step for 'project_libwebrtc'
FAILED: external/libwebrtc/stamp/project_libwebrtc-download /Users/brandonros/Desktop/node-webrtc/build/external/libwebrtc/stamp/project_libwebrtc-download 
cd /Users/brandonros/Desktop/node-webrtc/build/external/libwebrtc/download && /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E env DEPOT_TOOLS=/Users/brandonros/Desktop/node-webrtc/build/external/depot_tools/src PLATFORM=darwin WEBRTC_REVISION=branch-heads/4280 /Users/brandonros/Desktop/node-webrtc/scripts/download-webrtc.sh && /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E touch /Users/brandonros/Desktop/node-webrtc/build/external/libwebrtc/stamp/project_libwebrtc-download

export PATH=$DEPOT_TOOLS:$PATH

gclient config --unmanaged --spec 'solutions=[{"name":"src","url":"https://webrtc.googlesource.com/src.git"}]'
depot_tools update failed. Conflict in /Users/brandonros/Desktop/node-webrtc/build/external/depot_tools/src
fatal: invalid upstream 'origin/master'
Platform mac-arm64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file.
Traceback (most recent call last):
  File "/Users/brandonros/Desktop/node-webrtc/build/external/depot_tools/src/gclient.py", line 99, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
[12/117] Performing download step (git clone) for 'project_catch2'
Cloning into 'src'...
HEAD is now at a1cdff4f raspigcd - opensource-users
ninja: build stopped: subcommand failed.
Build failed
/Users/brandonros/Desktop/node-webrtc/scripts/build-from-source.js:34
    throw new Error('ncmake build failed for wrtc');
    ^

Error: ncmake build failed for wrtc
    at main (/Users/brandonros/Desktop/node-webrtc/scripts/build-from-source.js:34:11)
    at main (/Users/brandonros/Desktop/node-webrtc/scripts/download-prebuilt-or-build-from-source.js:19:3)
    at Object.<anonymous> (/Users/brandonros/Desktop/node-webrtc/scripts/download-prebuilt-or-build-from-source.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.14.2
npm ERR! code 1
npm ERR! path /Users/brandonros/Desktop/node-webrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt-or-build-from-source.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brandonros/.npm/_logs/2023-06-08T20_33_38_659Z-debug-0.log
```

**Comment by brandonros** [comment]
just use this https://github.com/koush/node-webrtc
