### ISSUE TITLE
'npm install wrtc' always failed with http error 503, but wget the tarball succeeded. 

### ISSUE THREAD

**Issue by wanted002** [node-webrtc/node-webrtc#757]
When I run command 'npm install wrtc', it always failed. My OS is ubuntu20.04. Please help me out of this ... Many thanks.

Errors shown on my terminal:
npm ERR! command failed
npm ERR! command sh -c -- node scripts/download-prebuilt.js
npm ERR! 503 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/linux-x64.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@16.18.0 | linux | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/wd/code/electron-app/webrtc/node_modules/wrtc/build/Release/wrtc.node" (not found)
npm ERR! node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/linux-x64.tar.gz
npm ERR! node-pre-gyp http 503 https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: 503 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/home/wd/code/electron-app/webrtc/node_modules/node-pre-gyp/lib/install.js:142:27)
npm ERR! node-pre-gyp ERR! stack     at PassThrough.emit (node:events:525:35)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/wd/code/electron-app/webrtc/node_modules/needle/lib/needle.js:538:9)
npm ERR! node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:628:26)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR! node-pre-gyp ERR! stack     at Socket.socketOnData (node:_http_client:534:22)
npm ERR! node-pre-gyp ERR! stack     at Socket.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:315:12)
npm ERR! node-pre-gyp ERR! System Linux 5.4.18-91-generic
npm ERR! node-pre-gyp ERR! command "/home/wd/.n/bin/node" "/home/wd/code/electron-app/webrtc/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /home/wd/code/electron-app/webrtc/node_modules/wrtc
npm ERR! node-pre-gyp ERR! node -v v16.18.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.17.0
npm ERR! node-pre-gyp ERR! not ok

Here is the log:
[2023-07-07T09_42_26_058Z-debug-0.log](https://github.com/node-webrtc/node-webrtc/files/11980445/2023-07-07T09_42_26_058Z-debug-0.log)

**Comment by john-m24** [comment]
+1 except I'm getting a "404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz" error when trying to install on macOS M1
